apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: podinfo
  namespace: flux-system
spec:
  checkout:
    gitRepositoryRef:
      name: flux-system
    branch: main
    paths:
      - ./clusters/minikube
  interval: 1m
  commit:
    author:
      email: fluxcdbot@users.noreply.github.com
      name: fluxcdbot

